# Generated by Django 3.2.6 on 2024-08-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='category name', unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='categories',
            new_name='content_type',
        ),
        migrations.AlterField(
            model_name='ads',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AdsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ads')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.ManyToManyField(through='main.AdsCategory', to='main.Category'),
        ),
    ]
