# Generated by Django 3.2.6 on 2024-08-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240813_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
