# Generated by Django 3.2.6 on 2024-08-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240816_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='user_id',
            new_name='user',
        ),
    ]
